name: release

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: ./build.bat

    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        title: Latest release
        files: ./dist/tetris-c.exe